---
- name: install nginx
  include_tasks: install.yml

- name: Ensure data directories for virtual sites exists
  file:
    path: "{{ item.root_path }}"
    state: directory
    owner: "{{ nginx_system_user }}"
    group: "{{ nginx_system_group }}"
  when: item.root_path is defined
  with_items:
    "{{ nginx_site_configs }}"

- name: configure nginx
  include_tasks: base_conf.yml

- name: setup geoip2 module
  include_tasks: setup_geoip2.yml
  when: nginx_module_geoip2_enabled

- name: setup vhosts
  include_tasks: setup_vhost.yml
  with_items:
    - "{{ nginx_site_configs }}"

