---
- name: install nginx
  import_tasks: install.yml
  tags: [ install ]

- name: Ensure data directories for virtual sites exists
  file:
    path: "{{ item.root_path }}"
    state: directory
    owner: "{{ nginx_system_user }}"
    group: "{{ nginx_system_group }}"
  when: item.root_path is defined
  with_items:
    "{{ nginx_site_configs }}"
  tags: [ init ]

- name: configure nginx
  import_tasks: base_conf.yml
  tags: [ config ]

- name: configure certs
  include_tasks: copy_certs.yml

- name: setup geoip2 module
  import_tasks: setup_geoip2.yml
  when: nginx_module_geoip2_enabled
  tags: [ install ]

- name: setup vhosts
  include_tasks:
    file: setup_vhost.yml
    apply:
      tags: [ config ]
  with_items:
    - "{{ nginx_site_configs }}"
  tags: [ config ]
