---
- name: nginx restart
  debug: msg="checking config first"
  changed_when: True
  notify:
    - check nginx configuration
    - nginx restart - after config check

- name: nginx reload
  debug: msg="checking config first"
  changed_when: True
  notify:
    - check nginx configuration
    - nginx reload - after config check

- name: checking nginx configuration
  command: "nginx -t -c {{ nginx_conf_dir }}/nginx.conf"
  register: result
  changed_when: "result.rc != 0"
  check_mode: no
  listen: "check nginx configuration"

- name: nginx check stdout
  debug:
    msg: "{{ result.stdout  }}"
  listen: "check nginx configuration"

- name: nginx check stderr
  debug:
    msg: "{{ result.stderr }}"
  listen: "check nginx configuration"

- name: nginx restart - after config check
  service: name=nginx state=restarted

- name: nginx reload - after config check
  service: name=nginx state=reloaded


