---
- name: nginx restart
  debug: msg="checking config first"
  changed_when: True
  notify:
    - check nginx configuration
    - nginx restart - after config check

- name: nginx reload
  debug: msg="checking config first"
  changed_when: True
  notify:
    - check nginx configuration
    - nginx reload - after config check

- name: check nginx configuration
  command: "nginx -t -c {{ nginx_conf_dir }}/nginx.conf"
  register: result
  changed_when: "result.rc != 0"
  check_mode: no

- name: nginx restart - after config check
  service: name=nginx state=restarted

- name: nginx reload - after config check
  service: name=nginx state=reloaded


